version: '3.4'

services:
  tor-router:
    image: registry.gitlab.com/yoanndelattre/tor-router-docker:latest
    container_name: tor-router
    hostname: tor-router
    restart: always
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    ports:
      - 5353:53/udp
      - 9050:9050