version: '3.4'

services:
  tor-router:
    image: registry.gitlab.com/yoanndelattre/tor-router-docker:latest
    container_name: tor-router
    hostname: tor-router
    restart: always
    ports:
      - 9050:9050
      - 53:5353/udp
    volumes:
      - tor_data:/tor_data

volumes:
  tor_data: