version: '3.4'

services:
  tor-router:
    image: ghcr.io/yoanndelattre/tor-router-docker:main
    container_name: tor-router
    hostname: tor-router
    restart: always
    ports:
      - 9050:9050
    volumes:
      - tor_data:/tor_data

volumes:
  tor_data:
