name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        shell: bash

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
        shell: bash

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --push .
        shell: bash